Implementation of the larger part of all credentials of proeftuin. Missing the PID, the AcademicBaseCredential_SD, and the sandbox _JWT, _LD and _SD variants

diff --git a/scripts/proeftuin/check_credential b/scripts/proeftuin/check_credential
--- a/scripts/proeftuin/check_credential
+++ b/scripts/proeftuin/check_credential
@@ -3,12 +3,37 @@
 TENANT=$1
 CRED=$2
 DIR=$3
-CTYPE=$4
-BASEURL=$5
+BASEURL=$4
 
-KEYS=`cat credentials/${CRED}.json | jq -r '.data | keys | join(",")'`
-TYPE=`cat credentials/${CRED}.json | jq -r '.type'`
+HASFULLCRED=0
+DATA=`cat credentials/${CRED}.json | jq -r '.data'`
+if [ "x$DATA" = "x" -o "x$DATA" = "xnull" ]
+then
+    CREDDATA=`cat credentials/${CRED}.json | jq -r '.credential'`
+
+    if [ "x$CREDDATA" = "x" -o "x$CREDDATA" = "xnull" ]
+    then
+        echo "ERROR: Input credential does not have data or credential information"
+        exit 1
+    fi
+    HASFULLCRED=1
+fi
+
+CREDID=`cat credentials/${CRED}.json | jq -r '.credential_id'`
+CTYPE=`cat credentials/${CRED}.json | jq -r '.type'`
 CREDENTIAL=`cat $DIR/${TENANT}_${CRED}_credential.json | jq -r '.credentials[0].credential'`
+
+if [ "$HASFULLCRED" = "0" ]
+then
+    KEYS= `cat credentials/${CRED}.json | jq -r '.data | keys | join(",")'`
+else
+    KEYS=""
+    if [ "x$CTYPE" = "xvc2" ]
+    then
+        KEYS=`cat credentials/${CRED}.json | jq -r '.credential.credentialSubject | keys | join(",")'`
+    fi
+fi
+
 
 if [ "x$CTYPE" = "xvc1" -o "x$CTYPE" = "xvc2" ]
 then
@@ -65,9 +90,9 @@ then
         exit 1
     fi
     TYPE2=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.payload.type | join(",")'`
-    if [ ! "x$TYPE2" = "xVerifiableCredential,$TYPE" ]
+    if [ ! "x$TYPE2" = "xVerifiableCredential,$CREDID" ]
     then
-        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect type attribute ('$TYPE2' vs 'VerifiableCredential,$TYPE')"
+        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect type attribute ('$TYPE2' vs 'VerifiableCredential,$CREDID')"
         exit 1
     fi
 
@@ -98,12 +123,12 @@ yarn --cwd ../.. do resolve -k $ISS > $DIR/issuer_key.json
 
 if [ "x$CTYPE" = "xvc1" -o "x$CTYPE" = "xvc2" ]
 then
-    KID=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq '.header.kid'`
+    KID=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.header.kid'`
     # our did:web implementation should always return a #0 key reference
-    if [ ! "x$KID" = "x$ISS#0" ]
+    if [ ! "x$KID" = "x$ISS#0" -a ! "x$KID" = "x#0" ]
     then
         echo "ERROR: $TENANT - $CRED Invalid keyid $KID"
-        #exit 1
+        exit 1
     fi
 
     # for the signature verification, we should actually use KID, but in our
@@ -121,23 +146,36 @@ fi
 IFS=',' read -ra keys <<< "$KEYS"
 for key in ${keys[@]}
 do
-    echo "Checking claim $key"
-    if [ "x$CTYPE" = "xvc2" ]
+    # skip accidentally checking the credentialSubject.id
+    if [ ! "x$key" = "xid" ]
     then
-        CONTENT=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq ".payload.credentialSubject.[\"$key\"]"`       
-    fi
+        echo "Checking claim $key"
+        if [ "x$CTYPE" = "xvc2" ]
+        then
+            CONTENT=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq ".payload.credentialSubject.[\"$key\"]"`       
+        fi
 
-    if [ "x$CONTENT" = "x" -o "x$CONTENT" = "xnull" ]
-    then
-        echo "ERROR: $TENANT - $CRED Missing claim $key in credential ('$CONTENT')"
-        exit 1
-    fi
+        if [ "x$CONTENT" = "x" -o "x$CONTENT" = "xnull" ]
+        then
+            echo "ERROR: $TENANT - $CRED Missing claim $key in credential ('$CONTENT')"
+            exit 1
+        fi
 
-    DATA=`cat credentials/${CRED}.json | jq ".data.[\"$key\"]"`
-    if [ ! "x$DATA" = "x$CONTENT" ]
-    then
-        echo "ERROR: $TENANT - $CRED Claim in credential ('$CONTENT') does not match original ('$DATA')"
-        exit 1
+        if [ "$HASFULLCRED" = "0" ]
+        then
+            DATA=`cat credentials/${CRED}.json | jq ".data.[\"$key\"]"`
+        else
+            if [ "x$CTYPE" = "xvc2" ]
+            then
+                DATA=`cat credentials/${CRED}.json | jq ".credential.credentialSubject.[\"$key\"]"`
+            fi
+        fi
+
+        if [ ! "x$DATA" = "x$CONTENT" ]
+        then
+            echo "ERROR: $TENANT - $CRED Claim in credential ('$CONTENT') does not match original ('$DATA')"
+            exit 1
+        fi
     fi
 done
 
